### Planets Index
GET http://localhost:3000/planets.as_json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

### Planets Show
GET http://localhost:3000/planets/1.as_json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

### Planets Create
POST http://localhost:3000/planets.as_json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

{
  "system_id": 1,
  "name": "Tau-Delta",
  "diameter": 140000,
  "mass": 224,
  "orbital_distance": 17.6,
  "description": "Amonia gas giant with rings.",
  "image": "",
  "is_star": false
}

### Planets Edit
PATCH http://localhost:3000/planets/5.as_json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

{
  "system_id": 1,
  "name": "Tau-Beta",
  "diameter": 23000,
  "mass": 12.7,
  "orbital_distance": 2.3,
  "description": "Barren world comprised of silicon and iron.",
  "image": "",
  "is_star": false
}

### Planets Destroy
DELETE http://localhost:3000/planets/5.as_json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

### Systems Index
GET http://localhost:3000/systems.as_json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

### Systems Show
GET http://localhost:3000/systems/1.as_json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

### Systems Create
POST http://localhost:3000/systems.as_json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

{
  "user_id": 1,
  "name": "New Sol",
  "image": "",
  "description": "Home star of Earth."
}

### Systems Edit
PATCH http://localhost:3000/systems/7.as_json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

{
  "user_id": 1,
  "name": "OLD Sol",
  "image": "",
  "description": "Home star of Earth."
}

### Systems Destroy
DELETE http://localhost:3000/systems/7.as_json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

### Users Create 
POST http://localhost:3000/users.as_json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

{
  "username": "MyManMonday",
  "email": "monday@test.com",
  "password": "monday",
  "password_confirmation": "monday" 
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc4Njk5MzN9.RiEStvNi0x4kkUS0uTifOF6lTPt4c4pDdJzTUwK_Zh8

{
  "email": "friday@test.com",
  "password": "friday"
}
